spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

---

spring:
  profiles: dev
  cache:
    type: simple
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Desktop/h2/hpvm;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa

logging:
  level:
    org.hibernate.SQL: debug
    com.tsingyun: debug

---

spring:
  profiles: prod
  cache:
    type: simple
  session:
    store-type: jdbc
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    com.tsingyun: INFO
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

